# Generated by Django 2.2.3 on 2019-09-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0003_auto_20190910_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
