# Generated by Django 2.2.3 on 2019-09-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0008_auto_20190911_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
